--------------------------------------------------------
--  Constraints for Table AA_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AA_CUSTOMER" ADD CONSTRAINT "AA_DETEILCUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("ACCOUNT_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("E_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
